openapi: 3.0.0
info:
  title: Electronics Shop API
  description: API for an online electronics shop.
  version: 1.1.0
servers:
  - url: http://localhost:3001/api
    description: Development server

tags:
  - name: Products
    description: Product catalog operations
  - name: Users
    description: User authentication and management
  - name: Authentication
    description: Social login and external authentication providers.
  - name: Cart
    description: Shopping cart operations
  - name: Wishlist
    description: User wishlist operations
  - name: Orders
    description: Order management and history
  - name: User Profile
    description: Operations related to the authenticated user's profile.
  - name: Support
    description: Customer support tickets and FAQs
  - name: Staff
    description: Operations for staff members
  - name: Admin
    description: (Admin Only) System-wide user management.

paths:
  $ref: './paths/products.yaml'
  $ref: './paths/users.yaml'
  $ref: './paths/auth.yaml'
  $ref: './paths/cart.yaml'
  $ref: './paths/wishlist.yaml'
  $ref: './paths/orders.yaml'
  $ref: './paths/support.yaml'
  $ref: './paths/staff.yaml'
  $ref: './paths/admin.yaml'

components:
  schemas:
    $ref: './components/schemas.yaml'
  requestBodies:
    $ref: './components/requestBodies.yaml'
  securitySchemes:
    $ref: './components/securitySchemes.yaml'
